# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6ibohE1ChukYJ7LEgidVg3a6fWS5g-s
"""
step1 : install python-bar-code
pip install python-barcode
step2: import barcode
import barcode
step3: import image writer
from barcode.writer import ImageWriter
 step4 : enter the number so it generate a barcode
number=input('enter the code to generate barcode')
barcode_formate=barcode.get_barcode_class('upc')
my_barcode=barcode_formate(number,writer=ImageWriter())
my_barcode.save('barcode.png')
step5 the barcode is store in directory that your file location or if you did golab then /content/barcode.png.png this will be directory
from PIL import Image

image=Image.open(r'/content/barcode.png.png')
image





